### YamlMime:ManagedReference
items:
- uid: PegasusEngine.Renderer.RenderSettings
  commentId: T:PegasusEngine.Renderer.RenderSettings
  id: RenderSettings
  parent: PegasusEngine.Renderer
  children:
  - PegasusEngine.Renderer.RenderSettings.#ctor
  - PegasusEngine.Renderer.RenderSettings.Reset
  langs:
  - csharp
  - vb
  name: RenderSettings
  nameWithType: RenderSettings
  fullName: PegasusEngine.Renderer.RenderSettings
  type: Struct
  source:
    remote:
      path: PegasusEngine/src/Renderer/RenderSettings.cs
      branch: master
      repo: https://github.com/Martinecko30/PegasusEngine.git
    id: RenderSettings
    path: ../PegasusEngine/src/Renderer/RenderSettings.cs
    startLine: 2
  assemblies:
  - PegasusEngine
  namespace: PegasusEngine.Renderer
  syntax:
    content: public struct RenderSettings
    content.vb: Public Structure RenderSettings
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: PegasusEngine.Renderer.RenderSettings.#ctor
  commentId: M:PegasusEngine.Renderer.RenderSettings.#ctor
  id: '#ctor'
  parent: PegasusEngine.Renderer.RenderSettings
  langs:
  - csharp
  - vb
  name: RenderSettings()
  nameWithType: RenderSettings.RenderSettings()
  fullName: PegasusEngine.Renderer.RenderSettings.RenderSettings()
  type: Constructor
  source:
    remote:
      path: PegasusEngine/src/Renderer/RenderSettings.cs
      branch: master
      repo: https://github.com/Martinecko30/PegasusEngine.git
    id: .ctor
    path: ../PegasusEngine/src/Renderer/RenderSettings.cs
    startLine: 6
  assemblies:
  - PegasusEngine
  namespace: PegasusEngine.Renderer
  syntax:
    content: public RenderSettings()
    content.vb: Public Sub New()
  overload: PegasusEngine.Renderer.RenderSettings.#ctor*
  nameWithType.vb: RenderSettings.New()
  fullName.vb: PegasusEngine.Renderer.RenderSettings.New()
  name.vb: New()
- uid: PegasusEngine.Renderer.RenderSettings.Reset
  commentId: M:PegasusEngine.Renderer.RenderSettings.Reset
  id: Reset
  parent: PegasusEngine.Renderer.RenderSettings
  langs:
  - csharp
  - vb
  name: Reset()
  nameWithType: RenderSettings.Reset()
  fullName: PegasusEngine.Renderer.RenderSettings.Reset()
  type: Method
  source:
    remote:
      path: PegasusEngine/src/Renderer/RenderSettings.cs
      branch: master
      repo: https://github.com/Martinecko30/PegasusEngine.git
    id: Reset
    path: ../PegasusEngine/src/Renderer/RenderSettings.cs
    startLine: 12
  assemblies:
  - PegasusEngine
  namespace: PegasusEngine.Renderer
  syntax:
    content: public void Reset()
    content.vb: Public Sub Reset()
  overload: PegasusEngine.Renderer.RenderSettings.Reset*
references:
- uid: PegasusEngine.Renderer
  commentId: N:PegasusEngine.Renderer
  href: PegasusEngine.html
  name: PegasusEngine.Renderer
  nameWithType: PegasusEngine.Renderer
  fullName: PegasusEngine.Renderer
  spec.csharp:
  - uid: PegasusEngine
    name: PegasusEngine
    href: PegasusEngine.html
  - name: .
  - uid: PegasusEngine.Renderer
    name: Renderer
    href: PegasusEngine.Renderer.html
  spec.vb:
  - uid: PegasusEngine
    name: PegasusEngine
    href: PegasusEngine.html
  - name: .
  - uid: PegasusEngine.Renderer
    name: Renderer
    href: PegasusEngine.Renderer.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: PegasusEngine.Renderer.RenderSettings.#ctor*
  commentId: Overload:PegasusEngine.Renderer.RenderSettings.#ctor
  href: PegasusEngine.Renderer.RenderSettings.-ctor.html#PegasusEngine_Renderer_RenderSettings__ctor
  name: RenderSettings
  nameWithType: RenderSettings.RenderSettings
  fullName: PegasusEngine.Renderer.RenderSettings.RenderSettings
  nameWithType.vb: RenderSettings.New
  fullName.vb: PegasusEngine.Renderer.RenderSettings.New
  name.vb: New
- uid: PegasusEngine.Renderer.RenderSettings.Reset*
  commentId: Overload:PegasusEngine.Renderer.RenderSettings.Reset
  href: PegasusEngine.Renderer.RenderSettings.Reset.html#PegasusEngine_Renderer_RenderSettings_Reset
  name: Reset
  nameWithType: RenderSettings.Reset
  fullName: PegasusEngine.Renderer.RenderSettings.Reset
memberLayout: SeparatePages
